import OperatorSources from "../components/OperatorSources";
import { pageMetadata } from "./seo";
import { operators } from "./operators";
import { fivegOperators, fivegUpdated } from "./fiveg";
import { languageAlternates } from "./languages";

export const englishPages = [
  {
    path: "/en",
    arabicPath: "/",
    nav: "Internet in Saudi Arabia",
    title: "5G Home Internet & Fiber in Saudi Arabia | Saudi Wasel",
    description: "Moving to Saudi Arabia? Compare home 5G and fiber options, check your address and get English-speaking help on WhatsApp.",
    h1: "5G Home Internet & Fiber in Saudi Arabia",
    eyebrow: "A new home. A connection that fits.",
    service: "5G home internet and fiber",
    intro: "Make your new Saudi home feel connected from the start. A plug-in 5G router keeps setup simple without fixed cabling, while fiber is worth exploring for a longer stay. We help you compare providers, choose a plan that fits your lease and get started with friendly English support.",
    contextTitle: "Start with your home, not just a speed number",
    context: "Tell us about your home, the people sharing your connection and your everyday internet use. From a temporary apartment to a family rental, we help you balance setup, payment options and your next move. Service availability depends on your exact address; we check it before you choose.",
    points: ["No fixed cabling for a 5G router", "Fiber checked at the building level", "English-speaking help from enquiry to activation"],
    operatorIntro: "Explore STC, Zain, Salam and Mobily with one English-speaking contact. We explain the differences in equipment, payment periods and setup so you can make a comfortable choice.",
    plansIntro: "Use these earlier plan names only as references. Current pricing, speeds, equipment and offer periods must be confirmed in the official operator source for your exact address.",
    operators: [
      ["STC", "STC offers home 5G routers and fiber, including monthly subscriptions and prepaid packages for different lengths of stay."],
      ["Zain", "Zain's 5G+ home range includes everyday, gaming and entertainment packages with different router and Wi-Fi extras."],
      ["Salam", "Compare Salam options for the home you actually use, and confirm equipment requirements and installation conditions in its official current offer."],
      ["Mobily", "Mobily provides Home 5G router packages and Home Fiber plans, letting you compare wireless setup with a fixed connection."],
    ],
    requirements: ["A valid Iqama or Saudi National ID for the operator's eligibility checks.", "Your National Address or the exact building location, not just the city name.", "A mobile number where you can receive updates about your application."],
    steps: [
      ["Send your location", "Share your city, area and a building map pin on WhatsApp."],
      ["We check coverage", "We review which home internet services can be requested at that address."],
      ["Choose a plan", "Compare the confirmed price, commitment and router or installation terms."],
      ["Activation", "We follow up on the order; the operator confirms approval and activation arrangements."],
    ],
    benefits: [
      ["Quick WhatsApp replies", "Get a direct response to your home internet enquiry without starting separate conversations for every provider."],
      ["English support", "Discuss documents, plan conditions and the next steps in clear English."],
      ["Compare operators", "See the eligible choices side by side rather than selecting a network on name alone."],
      ["Order follow-up", "Stay informed as the application progresses towards the operator's activation."],
    ],
    faqs: [
      { q: "Can an expat apply for home internet with an Iqama?", a: "Yes. Start with your valid Iqama, home location and mobile number. We guide you through the provider's identity checks and application documents." },
      { q: "Should I choose fiber or a 5G home router when renting?", a: "5G avoids fixed cabling and may suit a short lease. Fiber can suit a longer stay if the building is eligible and you can arrange installation permission. Compare both against your work and household needs." },
      { q: "Are prepaid and postpaid plans available?", a: "Earlier plan-name references include monthly and prepaid examples; confirm which are currently available with STC. We help you compare upfront costs, payment schedules and commitment before applying." },
      { q: "Can I keep my router when I move home?", a: "Review the plan's relocation rules before your move. Share the new home details with us and we help arrange the next steps with your provider." },
      { q: "What does a coverage check need?", a: "Send your city, neighbourhood and a map pin for your building. For fiber, include your unit details; for 5G, tell us where you plan to place the router." },
      { q: "Can Saudi Wasel help me in English?", a: "Absolutely. Message us in English on WhatsApp or call 0564612017 for help comparing plans, preparing documents and following your order." },
    ],
  },
  {
    path: "/en/5g-home-internet-jeddah",
    arabicPath: "/jeddah/5g",
    nav: "5G home internet in Jeddah",
    title: "5G Home Internet Jeddah | Prepaid & Postpaid Plans 2026",
    description: "Explore 5G home internet in Jeddah for expats and renters. Check your address and ask about prepaid or postpaid router plans in English.",
    h1: "5G Home Internet in Jeddah",
    eyebrow: "Jeddah / Internet for your rental",
    city: "Jeddah",
    service: "5G home internet",
    intro: "Settle into your Jeddah rental with a connection of your own. A 5G home router plugs in without fiber cabling or a fiber installation visit, making it a practical choice for furnished flats and rental homes. We help you compare monthly and prepaid packages and handle the application in English.",
    contextTitle: "From a furnished flat to a compound home",
    context: "Start by checking whether your Jeddah lease includes internet, then decide whether you want a separate connection for work, streaming or sharing with flatmates. Tell us your housing type and where the router would sit. Availability depends on your apartment's exact address, which we check as part of your enquiry.",
    points: ["A separate connection for a furnished rental", "Prepaid and postpaid enquiries welcome", "Check indoor reception before choosing"],
    operatorIntro: "Compare four home internet providers for your Jeddah rental. We walk you through router equipment, payment periods and the details that matter for your stay.",
    plansIntro: "Use these earlier plan names only as references. Current pricing, speeds, equipment and offer periods must be confirmed in the official operator source for your exact address.",
    operators: [
      ["STC", "STC's Baity 5G range combines monthly home-router subscriptions with prepaid periods, useful when comparing different rental lengths."],
      ["Zain", "Zain offers 5G+ home packages with router, Wi-Fi extender and entertainment bundles across its range."],
      ["Salam", "Compare Salam options for the home you actually use, and confirm equipment requirements and installation conditions in its official current offer."],
      ["Mobily", "Mobily Home 5G comes in several speed tiers with a router, alongside its separate Home Fiber range."],
    ],
    areas: [
      ["Al Hamra", "Considering an Al Hamra apartment? Ask whether Wi-Fi is part of the rent and whether it is shared with other units. A separate home router is worth comparing if you want to manage your own subscription."],
      ["Al Rawdah", "For an Al Rawdah family rental, list the devices that will be online together, from work laptops to streaming screens. This helps you choose a package and plan Wi-Fi placement around the rooms you use most."],
      ["Al Zahra", "Moving into a furnished flat in Al Zahra? Compare the prepaid payment period with your lease dates, and include equipment costs in your budget rather than looking at the monthly fee alone."],
      ["Obhur", "When viewing an Obhur home, think about where everyone needs Wi-Fi, especially if the property has several floors. Share the layout with us to discuss router position and whether extra Wi-Fi equipment would be useful."],
      ["Al Shati", "For an Al Shati rental used for video meetings, choose a practical router spot close to your workspace. Tell us about your working hours and upload needs so the comparison reflects your daily routine."],
    ],
    requirements: ["Your valid Iqama or National ID for the subscription application.", "A National Address or map pin for the Jeddah building where the router will be used.", "A working mobile number for application and activation messages."],
    steps: [
      ["Send your location", "Tell us your Jeddah area and share the location of the apartment or compound."],
      ["We check coverage", "We check eligible networks for the address and explain indoor-signal considerations."],
      ["Choose a plan", "Review available payment types, router terms and any commitment before selecting."],
      ["Activation", "After approval, we help follow up on the router order and the operator's activation process."],
    ],
    benefits: [
      ["Fast WhatsApp contact", "Send one Jeddah enquiry and get a prompt reply about the checks needed."],
      ["Help in English", "Ask about your rental, the paperwork or a plan condition without translating the conversation."],
      ["A wider comparison", "We review the operators relevant to your address, not just the first advertised offer."],
      ["Follow-through", "We keep track of the request with you until the operator confirms the next activation steps."],
    ],
    faqs: [
      { q: "Can I apply for 5G home internet in Jeddah with an Iqama?", a: "Yes, a valid Iqama is the starting document. Send your Jeddah home details and contact number, and we explain the provider's verification steps." },
      { q: "Is there a prepaid router option for a short stay in Jeddah?", a: "Check whether STC currently offers a prepaid period that matches your Jeddah lease; earlier examples are not confirmed current offers. Compare the full payment period with your stay and review the equipment and cancellation terms with us." },
      { q: "Will a 5G router work inside my compound apartment?", a: "Router placement makes a difference indoors. Tell us about your apartment layout and any compound equipment rules so we can discuss a sensible setup." },
      { q: "Can I take the router to another apartment in Jeddah?", a: "Some plans include relocation or mobility options. Before moving, ask us to review your subscription's rules and help coordinate the change with the operator." },
      { q: "Do I need a landlord's permission to install a 5G router?", a: "A plug-in 5G home router does not need fixed fiber cabling. Check your tenancy or compound rules for any restrictions on your own internet equipment." },
      { q: "Can you arrange my Jeddah enquiry in English?", a: "Yes. Message us in English with your Jeddah area and housing type. We explain the available choices and follow up on the application." },
    ],
  },
  {
    path: "/en/5g-home-internet-riyadh",
    arabicPath: "/riyadh",
    nav: "5G home internet in Riyadh",
    title: "5G Home Internet Riyadh | Router Plans & Coverage Check",
    description: "Find a 5G home router for your Riyadh rental. Compare operators, check your location and get English support with your application.",
    h1: "5G Home Internet in Riyadh",
    eyebrow: "Riyadh / Settle in, stay connected",
    city: "Riyadh",
    service: "5G home internet",
    intro: "Starting a new job in Riyadh? Get your home internet organised alongside your move. A plug-in 5G router avoids fixed cabling and a fiber installation visit, keeping setup straightforward while you settle in. We help you weigh payment periods, equipment and your work-from-home needs in English.",
    contextTitle: "Internet that fits your Riyadh housing plans",
    context: "Your first Riyadh apartment may be a stepping stone to a longer lease. Match the subscription to that timeline, and think about video calls, shared devices and Wi-Fi across the rooms you use. Service availability depends on your precise residential address; we check it before comparing plans.",
    points: ["A practical option while settling into a new job", "Discuss video calls and household use", "Recheck the address before a move"],
    operatorIntro: "Put STC, Zain, Salam and Mobily side by side for your Riyadh enquiry. We help you compare the home-router range against your lease and working routine.",
    plansIntro: "Use these earlier plan names only as references. Current pricing, speeds, equipment and offer periods must be confirmed in the official operator source for your exact address.",
    operators: [
      ["STC", "STC offers monthly Baity 5G and prepaid router packages, plus fiber for households comparing a longer-term fixed setup."],
      ["Zain", "For gaming, confirm Zain's current package features, equipment and service conditions; do not assume a dedicated IP or gaming benefit is included."],
      ["Salam", "Compare Salam options for the home you actually use, and confirm equipment requirements and installation conditions in its official current offer."],
      ["Mobily", "Mobily's home range includes both 5G router speed tiers and fiber packages, with equipment terms to confirm before ordering."],
    ],
    areas: [
      ["Al Olaya", "Choosing an Al Olaya flat for your Riyadh move? Check the rental's internet arrangements before adding a subscription. If you work from home, ask how shared Wi-Fi is managed and compare it with your own router."],
      ["Al Malqa", "For an Al Malqa household with several people online, think beyond a single device's download speed. Share the number of users and rooms so you can weigh the package alongside the home Wi-Fi setup."],
      ["Al Nakheel", "Viewing a rental in Al Nakheel? Note the best place for your desk and router while you inspect the apartment. A little setup planning helps keep work calls and everyday browsing convenient."],
      ["Hittin", "If your Hittin lease is a first step before a permanent home, compare prepaid periods with monthly commitments. Discuss relocation rules now so a later move is easier to organise."],
      ["Diplomatic Quarter area", "For a home in or around the Diplomatic Quarter area, ask management about included internet and rules for personal equipment. Give us the individual residence details rather than only the development name."],
    ],
    requirements: ["A valid resident Iqama or Saudi National ID for identity verification.", "The National Address or precise building pin for your Riyadh residence.", "Your mobile number so the provider can contact you about the request."],
    steps: [
      ["Send your location", "Share the Riyadh home address where you will use the connection, plus your housing type."],
      ["We check coverage", "We review services for that location and discuss signal checks inside the home."],
      ["Choose a plan", "Consider contract length, payment structure and your work-from-home requirements together."],
      ["Activation", "We track the application and help you understand the provider's setup instructions after approval."],
    ],
    benefits: [
      ["Prompt replies on WhatsApp", "Get the information needed to move your Riyadh enquiry forward without a store visit just to ask."],
      ["English explanations", "Understand commitment periods and application requirements in the language you prefer."],
      ["Provider comparison", "We put eligible plans in context for your lease and work routine."],
      ["Application follow-up", "Stay in touch about documents, operator responses and activation progress."],
    ],
    faqs: [
      { q: "Can a newly arrived Riyadh resident apply with an Iqama?", a: "Have your valid Iqama, residential location and mobile number ready. We help you prepare the application and complete the provider's verification process." },
      { q: "Is a prepaid plan suitable while I look for a permanent home?", a: "Prepaid can be useful for planning your upfront budget. Confirm the available payment periods with the operator, then compare them with your expected stay, including router obligations and any cancellation terms." },
      { q: "Can I move my router from a furnished flat to a Riyadh compound?", a: "Review your plan's relocation policy and the compound's personal-equipment rules first. We help you organise the move and understand any transfer steps." },
      { q: "Is home 5G reliable enough for remote work in Riyadh?", a: "Indoor signal, router position and busy network periods affect the experience. Tell us how often you take video calls or upload large files; we can compare a home router with fiber for that routine." },
      { q: "Does a larger apartment need more than one router?", a: "Start with the floor plan and the rooms where you use Wi-Fi most. A suitable router position or Wi-Fi extender may be more useful than buying a second home internet subscription." },
      { q: "Do you support Riyadh orders in English?", a: "Yes, we can discuss the location check, plan comparison and order updates in English over WhatsApp. Call 0564612017 if you prefer to speak directly." },
    ],
  },
  {
    path: "/en/5g-home-internet-khobar",
    arabicPath: "/khobar",
    nav: "5G home internet in Khobar",
    title: "5G Home Internet Khobar | Plans & English Support",
    description: "Explore 5G home internet for your Khobar apartment or compound. Request an address check and compare router plans with English help.",
    h1: "5G Home Internet in Khobar",
    eyebrow: "Khobar / Your own home connection",
    city: "Khobar",
    service: "5G home internet",
    intro: "Make your Khobar rental work for your routine with a home connection of your own. A 5G router needs no fixed fiber cable, so it is a practical option when you want to keep the property as it is. We help you compare providers, understand the paperwork and follow your order in English.",
    contextTitle: "For compound living and independent rentals",
    context: "Ask what your Khobar rent includes and how any existing internet is managed. Your own router can be worth comparing when you want a separate subscription for work or family use. Availability depends on the exact home address, including the individual residence inside a compound; we check that for you.",
    points: ["Check what your compound or lease includes", "Compare a private router with existing Wi-Fi", "Confirm terms for a future relocation"],
    operatorIntro: "Explore STC, Zain, Salam and Mobily for your Khobar home. We make the equipment, payment and relocation details easier to compare with your tenancy.",
    plansIntro: "Use these earlier plan names only as references. Current pricing, speeds, equipment and offer periods must be confirmed in the official operator source for your exact address.",
    operators: [
      ["STC", "STC's home services span Baity 5G and fiber, with prepaid packages alongside monthly payment options."],
      ["Zain", "Zain offers 5G+ home-router packages ranging from everyday use to gaming and premium entertainment bundles."],
      ["Salam", "Compare Salam options for the home you actually use, and confirm equipment requirements and installation conditions in its official current offer."],
      ["Mobily", "Mobily Home 5G offers multiple speed tiers and router equipment, while Home Fiber provides a fixed-line alternative."],
    ],
    areas: [
      ["Al Aqrabiyah", "Looking at an Al Aqrabiyah rental? Ask whether the advertised internet belongs to your unit or is shared across the building. That distinction helps you decide whether a personal router fits your needs."],
      ["Al Rakah", "For a home in Al Rakah, consider how your household splits time between online work, study and entertainment. Bring that usage pattern into the plan comparison instead of choosing on a speed label alone."],
      ["Al Olaya", "If you are choosing a furnished Al Olaya apartment in Khobar, align the internet payment period with your lease. Keep a note of any advance payment and equipment obligations before you sign up."],
      ["Al Yarmouk", "Planning a family connection in Al Yarmouk? Identify the rooms that need Wi-Fi and the devices that will be online together. We can help you discuss a practical router position and any extra Wi-Fi equipment."],
      ["Compounds area", "When comparing homes in Khobar's compounds area, speak to management about included internet, personal routers and installation access. Share the specific compound and unit with us so your enquiry reflects the home you are actually renting."],
    ],
    requirements: ["An in-date Iqama or National ID for identity and subscription eligibility checks.", "Your National Address or a map location identifying the Khobar building or compound residence.", "A mobile contact number for the operator and our order follow-up."],
    steps: [
      ["Send your location", "Tell us the Khobar area and pinpoint the residence, including a compound location if relevant."],
      ["We check coverage", "We review provider options and help you plan the router setup inside your home."],
      ["Choose a plan", "Compare the confirmed terms against your lease, existing internet and expected stay."],
      ["Activation", "We follow the order with you and clarify the operator's approval and activation updates."],
    ],
    benefits: [
      ["Quick WhatsApp response", "Get help narrowing down your Khobar home enquiry from the first message."],
      ["English-speaking assistance", "Discuss compound rules or subscription conditions without relying on literal translations."],
      ["Compare available networks", "Consider more than one operator when your address check allows it."],
      ["Continued order support", "We keep following the request rather than leaving you to interpret activation updates alone."],
    ],
    faqs: [
      { q: "What documents does an expat need for home 5G in Khobar?", a: "Start with a valid Iqama, your National Address or building location, and a mobile number. The provider confirms identity checks and any additional documents needed for the plan." },
      { q: "Can I order my own router inside a Khobar compound?", a: "Ask compound management about personal internet equipment and whether a connection is included in the rent. We help you compare a separate subscription with the existing arrangement." },
      { q: "Can you check prepaid home internet for a temporary Khobar stay?", a: "Yes. We help you confirm the current prepaid periods, total upfront payment and router terms so you can compare them with the dates of your stay." },
      { q: "Can the same home router be used at my workplace?", a: "Choose a subscription that explicitly permits use away from home. Ask us to review the location and usage rules with you before taking the router to work." },
      { q: "What if I move from Khobar to another Saudi city?", a: "Contact us before the move to review the operator's transfer policy. We help you understand whether a relocation request or a different subscription is the right next step." },
      { q: "Can I speak to someone in English about my Khobar order?", a: "Yes. Use WhatsApp in English to share your housing details and questions. We help compare the confirmed options and keep you informed about the application." },
    ],
  },
  {
    path: "/en/fiber-internet-jeddah",
    arabicPath: "/jeddah/stc",
    nav: "Fiber internet in Jeddah",
    title: "Fiber Internet Jeddah | STC, Salam & Mobily Plans",
    description: "Check fiber internet at your Jeddah building. Explore STC, Salam and Mobily, address checks and English-speaking application help.",
    h1: "Fiber Internet in Jeddah",
    eyebrow: "Jeddah / A connection for a longer stay",
    city: "Jeddah",
    service: "fiber internet",
    intro: "Planning a longer stay in Jeddah? Explore a fixed fiber connection for your household's work, streaming and everyday browsing. We help you compare plans, prepare the paperwork and coordinate installation. If you prefer to avoid cabling, we can also walk you through a plug-in 5G alternative.",
    contextTitle: "Check the building and the lease together",
    context: "Ask your Jeddah landlord or building manager about existing wiring, technician access and permission for any new cabling. Getting these details ready makes the installation conversation simpler. Fiber availability depends on your exact building and unit address; we check it before arranging your application.",
    points: ["Building-level eligibility comes first", "Agree installation access with the landlord", "Compare fiber with a no-cabling 5G option"],
    operatorIntro: "Compare the published fiber ranges from STC, Salam and Mobily, with Zain's home 5G range as a wireless alternative. We help you weigh installation, equipment and the length of your lease.",
    operators: [
      ["STC", "STC's Baity Fiber range includes monthly and annual prepaid packages, with installation and modem costs to confirm in the current offer."],
      ["Zain", "Zain's 5G+ home routers offer a no-fiber-cabling alternative, with everyday, gaming and entertainment packages."],
      ["Salam", "Salam's home fiber package includes router equipment; its HomeFi Max range offers a separate wireless option."],
      ["Mobily", "Mobily Home Fiber spans several speed tiers, including gaming and multi-room plans, with router and installation benefits."],
    ],
    areas: [
      ["Al Hamra", "For a longer lease in Al Hamra, ask the owner where the fiber cable would enter the apartment. Agreeing on the route and technician access early helps you prepare for installation without surprises."],
      ["Al Rawdah", "Comparing family homes in Al Rawdah? Note where the main router would sit and how Wi-Fi would reach bedrooms and living spaces. Plan the indoor network alongside your fiber subscription."],
      ["Al Zahra", "If you are renting in Al Zahra, ask the building manager about existing fiber wiring and access to shared utility spaces. Send your building and unit details when you enquire so the installation discussion is specific."],
      ["Obhur", "For an Obhur home with more than one floor, think about cabling routes and the rooms used for work or study. Discuss those needs before installation so the modem position supports your household layout."],
      ["Al Shati", "Settling into an Al Shati apartment for the year? Compare annual prepaid fiber with monthly subscriptions, and review transfer terms if your next lease might be elsewhere."],
    ],
    requirements: ["A valid Iqama or Saudi National ID, with final verification carried out by the fiber provider.", "The National Address or exact building location in Jeddah for the fiber check.", "A mobile number for application updates and coordination of the installation appointment."],
    steps: [
      ["Send your location", "Identify your Jeddah building and unit, and tell us whether you rent the property."],
      ["We check coverage", "We verify building-level fiber eligibility before discussing an installation request."],
      ["Choose a plan", "Review the available package, confirmed price, commitment and landlord-access requirements."],
      ["Activation", "We follow up on installation scheduling and the operator's service activation."],
    ],
    benefits: [
      ["Responsive WhatsApp help", "Get a quick reply about the address and building details needed for a fiber enquiry."],
      ["Clear English guidance", "Understand installation arrangements and the paperwork before agreeing to a package."],
      ["Compare eligible operators", "Compare payment periods, equipment and installation terms with clear guidance for your household."],
      ["Installation follow-up", "Keep one point of contact while the provider processes the request and arranges activation."],
    ],
    faqs: [
      { q: "Is fiber available in my Jeddah building?", a: "Send a map pin, your National Address and unit details. We use those details to request a building-level check and explain the next steps." },
      { q: "Can a tenant with an Iqama apply for fiber?", a: "Yes, prepare your valid Iqama and arrange landlord permission for any installation work. We help with the application documents and provider verification." },
      { q: "Are there prepaid STC fiber packages?", a: "The table retains earlier annual plan-name references, not a confirmed current prepaid offer. Ask STC which payment periods are available at your building. Compare the annual payment and included benefits with monthly plans, then ask us about the package you prefer." },
      { q: "How is fiber different from a 5G router for a furnished apartment?", a: "Fiber requires building eligibility and may involve technician access and cabling. A 5G router avoids fixed wiring, but its performance depends on indoor signal and the plan's location terms." },
      { q: "Can I transfer fiber when I leave my apartment?", a: "A move normally needs an operator transfer request and a coverage check for the new building. Confirm the policy and any charges before changing address." },
      { q: "Can you explain fiber installation in English?", a: "Yes. We can explain the documents, package conditions and installation follow-up in English. The operator confirms the actual appointment and activation arrangements." },
    ],
  },
  {
    path: "/en/fiber-vs-5g",
    arabicPath: "/fiber-vs-5g",
    nav: "Compare fiber vs 5G",
    title: "Fiber vs 5G Home Internet in Saudi Arabia | Saudi Wasel",
    description: "Fiber or a 5G router for your Saudi rental? Compare installation, moving home and everyday use, with address checks and English support.",
    h1: "Fiber vs 5G Home Internet in Saudi Arabia",
    eyebrow: "The right connection for your lease",
    service: "fiber and 5G home internet comparison",
    intro: "Choose home internet around the way you live, not just the biggest advertised speed. A 5G router keeps setup simple without fixed cabling; fiber brings a fixed connection worth comparing for a settled home and demanding daily use. We help you weigh installation, payment periods and your next move in clear English.",
    contextTitle: "Think about your next move as well as today",
    context: "For a short lease, start with the payment period and relocation terms. For a busy household, include video meetings, gaming and uploads in the comparison alongside cost. Service availability depends on your exact home address; we check fiber and 5G separately to help you choose.",
    points: ["Compare installation, not just download speeds", "Ask what happens when you change address", "Match the plan to your household's needs"],
    operatorIntro: "Choose the connection type and provider together. These home-service ranges give you a useful starting point for comparing a plug-in router with a fixed fiber installation.",
    plansIntro: "Use these earlier plan names only as references. Current pricing, speeds, equipment and offer periods must be confirmed in the official operator source for your exact address.",
    operators: [
      ["STC", "STC offers both Baity Fiber and Baity 5G, with monthly and prepaid packages to compare across the two connection types."],
      ["Zain", "Zain's 5G+ packages include routers and optional Wi-Fi or entertainment extras, offering a wireless home setup."],
      ["Salam", "Salam provides a choice of fiber and HomeFi Max wireless services, with different equipment setups for each."],
      ["Mobily", "Mobily pairs its Home Fiber range with Home 5G router packages, making installation and equipment useful comparison points."],
    ],
    requirements: ["A valid Iqama or National ID for an application to whichever operator you select.", "Your National Address or building pin so fiber and 5G can be checked separately.", "A mobile number for eligibility queries, order updates and any installation coordination."],
    steps: [
      ["Send your location", "Share the home address, length of stay and what you use the internet for."],
      ["We check coverage", "We assess fiber eligibility and home 5G options independently at that location."],
      ["Choose a plan", "Balance installation, signal, payment and commitment using the confirmed offers."],
      ["Activation", "We follow the selected route: a router order for 5G or installation arrangements for fiber."],
    ],
    benefits: [
      ["Quick answers on WhatsApp", "Ask the practical questions about your lease and connection before starting an application."],
      ["English-led comparison", "Talk through cabling, moving home and plan restrictions in everyday language."],
      ["Operator choice", "Compare providers as well as technologies when more than one option is eligible."],
      ["Follow-up after choosing", "We continue helping with the order once you have made the fiber-or-5G decision."],
    ],
    faqs: [
      { q: "Is fiber or 5G better for an expat renting in Saudi Arabia?", a: "A 5G router can be practical when you want to avoid cabling during a short lease. Fiber is worth exploring for a longer stay, especially when consistent everyday use and uploads are priorities. Compare commitment and relocation terms for both." },
      { q: "Which connection is easier to move to a new home?", a: "A router is easy to carry, but the subscription's mobility rules still matter. Fiber usually involves an operator transfer request and a new installation arrangement. We help you review the process before moving." },
      { q: "Is fiber always faster than a 5G home router?", a: "Not always. Fiber typically offers a steadier fixed connection, while 5G performance varies with indoor signal, placement and network demand. Compare the actual package and your household's usage rather than only the maximum download speed." },
      { q: "Can I apply for either service using an Iqama?", a: "Yes, use your valid Iqama to start the application for either service. We explain the provider's identity checks and any additional documents for your chosen package." },
      { q: "Does prepaid internet mean I can cancel without restrictions?", a: "Prepaid describes how you pay, not the cancellation policy. Review equipment obligations, advance payments and refund terms; we help you compare those details with a monthly subscription." },
      { q: "Can you help me compare fiber and 5G in English?", a: "Yes. Share your housing type, lease plans and main internet uses on WhatsApp. We explain the trade-offs and help you choose a connection that fits your routine." },
    ],
  },
];

export const englishDisclaimer = "Saudi Wasel is an independent sales agent and is not the official website of any telecom operator.";
export const priceEnquiry = "Contact us on WhatsApp for the latest plans and prices available at your address.";

export function englishMetadata(page) {
  return pageMetadata({
    title: page.title,
    description: page.description,
    alternates: { canonical: page.path, languages: languageAlternates(page.arabicPath) },
    openGraph: {
      title: page.title,
      description: page.description,
      url: page.path,
      locale: "en_SA",
      alternateLocale: "ar_SA",
      siteName: "Saudi Wasel",
      type: "website",
      images: [{ url: "/opengraph-image.png", alt: "Saudi Wasel home internet" }],
    },
    twitter: { card: "summary_large_image", title: page.title, description: page.description, images: ["/twitter-image.png"] },
  });
}

const stcPlanNames = {
  "بيتي فايبر بيسك": "Baity Fiber Basic",
  "بيتي ستريم لايت": "Baity Stream Lite",
  "بيتي فايبر ستريم": "Baity Fiber Stream",
  "بيتي فايبر انترتينمنت": "Baity Fiber Entertainment",
  "500 ميجا مسبق الدفع 12 شهر": "500 Mbps prepaid, 12 months",
  "300 ميجا مسبق الدفع 12 شهر": "300 Mbps prepaid, 12 months",
};

const stc = operators.find((operator) => operator.slug === "stc");
export const stcPricesUpdated = stc.updatedISO;
export const englishStcPlans = stc.packages.map((plan) => ({
  name: stcPlanNames[plan.name],
  down: "Confirm with operator",
  up: "Confirm with operator",
  price: "Unverified; check official source",
  perks: "Confirm equipment, installation and commitment",
}));

const fivegOperatorNames = { stc: "STC", salam: "Salam", zain: "Zain", mobily: "Mobily" };
const fivegPlanNames = {
  "بيتي 5G بيسك": "Baity 5G Basic",
  "بيتي 5G انترتينمنت": "Baity 5G Entertainment",
  "بيتي 5G لامحدود": "Baity 5G Unlimited",
  "5G مسبق الدفع 3 أشهر": "5G prepaid, 3 months",
  "5G مسبق الدفع 6 أشهر": "5G prepaid, 6 months",
  "5G مسبق الدفع 12 شهر": "5G prepaid, 12 months",
  "5G HomeFi 100": "5G HomeFi 100",
  "5G HomeFi 140": "5G HomeFi 140",
  "5G HomeFi 200": "5G HomeFi 200",
  "5G+ المنزلية الأساسية": "5G+ Home Basic",
  "5G+ المنزلية": "5G+ Home",
  "5G+ المنزلية للألعاب": "5G+ Home Gaming",
  "5G+ المنزلية برايم": "5G+ Home Prime",
  "5G+ المنزلية بلاك": "5G+ Home Black",
  "موبايلي هوم 5G 200 ميجا": "Mobily Home 5G 200 Mbps",
  "موبايلي هوم 5G 100 ميجا": "Mobily Home 5G 100 Mbps",
  "موبايلي هوم 5G 300 ميجا": "Mobily Home 5G 300 Mbps",
};




export const englishFivegUpdated = fivegUpdated.replace("سبتمبر", "September");
export const englishFivegOperators = fivegOperators.map((operator) => ({
  slug: operator.slug,
  name: fivegOperatorNames[operator.slug],
  packages: operator.packages.map((plan) => ({
    name: fivegPlanNames[plan.name],
    down: "Confirm with operator",
    up: "Confirm with operator",
    price: "Unverified; check official source",
    perks: "Confirm equipment and relocation conditions",
  })),
}));

export const connectionComparison = [
  ["Getting connected", "Building check, cabling if needed, and a technician appointment.", "A plug-in router; no fixed fiber cabling, once the operator activates service."],
  ["For a tenant", "Arrange landlord or management permission for installation work.", "No fixed wiring; check your tenancy or compound's equipment rules."],
  ["Connection consistency", "Typically a steadier fixed connection; actual service and plan still matter.", "Depends on indoor signal, router placement and network demand."],
  ["Uploads and gaming", "Often worth considering for frequent uploads or latency-sensitive use.", "Compare upload needs, router placement and the package's gaming features."],
  ["Moving home", "An operator transfer request and a check of the new building.", "Only where the subscription allows movement and the new location is suitable."],
  ["Setup planning", "Prepare building and unit details, plus permission for installation access.", "Choose a router position and consider Wi-Fi reach between rooms."],
  ["Plans and pricing", "Review the confirmed price, installation terms and commitment.", "Compare eligible prepaid or postpaid offers and router obligations."],
];
