import { operators } from "./operators";
import { languageAlternates } from "./languages";

export const englishPages = [
  {
    path: "/en",
    arabicPath: "/",
    nav: "Internet in Saudi Arabia",
    title: "5G Home Internet & Fiber in Saudi Arabia | Saudi Wasel",
    description: "Moving to Saudi Arabia? Compare home 5G and fiber options, check your address and get English-speaking help on WhatsApp.",
    h1: "5G Home Internet & Fiber in Saudi Arabia",
    eyebrow: "A new home. A connection that fits.",
    service: "5G home internet and fiber",
    intro: "Settling into a rental in Saudi Arabia? A 5G home router avoids fixed cabling and can get you connected without a fiber installation appointment once your order is approved. You may be able to take it to your next home, subject to the plan's location rules and coverage there.",
    contextTitle: "Start with your home, not just a speed number",
    context: "For an expat choosing between a temporary apartment and a longer lease, flexibility matters as much as the advertised speed. Tell us where you live, how many people share the connection and whether you work from home. We help you compare an address-checked 5G option with fiber that requires a separate building check.",
    points: ["No fixed cabling for a 5G router", "Fiber checked at the building level", "English-speaking help from enquiry to activation"],
    operatorIntro: "We help you explore STC, Zain, Salam and Mobily rather than assuming one network suits every home. The service and plans you can order depend on your address and the operator's checks.",
    operators: [
      ["STC", "Ask about home 5G or fiber, then review the contract and equipment terms."],
      ["Zain", "Include Zain's home internet options in your address check; do not assume 5G and fiber have the same availability."],
      ["Salam", "Consider Salam alongside other providers and confirm which services can be ordered at your location."],
      ["Mobily", "Compare Mobily's home connection choices with the other eligible plans before committing."],
    ],
    requirements: ["A valid Iqama or Saudi National ID for the operator's eligibility checks.", "Your National Address or the exact building location, not just the city name.", "A mobile number where you can receive updates about your application."],
    steps: [
      ["Send your location", "Share your city, area and a building map pin on WhatsApp."],
      ["We check coverage", "We review which home internet services can be requested at that address."],
      ["Choose a plan", "Compare the confirmed price, commitment and router or installation terms."],
      ["Activation", "We follow up on the order; the operator confirms approval and activation arrangements."],
    ],
    benefits: [
      ["Quick WhatsApp replies", "Get a direct response to your home internet enquiry without starting separate conversations for every provider."],
      ["English support", "Discuss documents, plan conditions and the next steps in clear English."],
      ["Compare operators", "See the eligible choices side by side rather than selecting a network on name alone."],
      ["Order follow-up", "Stay informed as the application progresses towards the operator's activation."],
    ],
    faqs: [
      { q: "Can an expat apply for home internet with an Iqama?", a: "You can request an eligibility check using a valid Iqama. Approval, identity verification and any additional requirements are decided by the operator." },
      { q: "Should I choose fiber or a 5G home router when renting?", a: "5G avoids fixed cabling and may suit a short lease. Fiber can suit a longer stay if the building is eligible and you can arrange installation permission. Compare both against your work and household needs." },
      { q: "Are prepaid and postpaid plans available?", a: "Ask us to check both payment types for your address and chosen service. Availability, advance payment and commitment vary by operator; we confirm the actual options before you apply." },
      { q: "Can I keep my router when I move home?", a: "Check your plan's movement restrictions and coverage at the new address first. A portable device does not automatically mean the subscription works at any location." },
      { q: "What does a coverage check need?", a: "Send your city, neighbourhood and exact building location. Fiber eligibility needs a building-level check, while indoor 5G performance also depends on signal and router placement." },
      { q: "Can Saudi Wasel help me in English?", a: "Yes. Send your enquiry in English on WhatsApp or call 0564612017. Saudi Wasel is an independent sales agent, not an operator's official website." },
    ],
  },
  {
    path: "/en/5g-home-internet-jeddah",
    arabicPath: "/jeddah/5g",
    nav: "5G home internet in Jeddah",
    title: "5G Home Internet Jeddah | Prepaid & Postpaid Plans 2026",
    description: "Explore 5G home internet in Jeddah for expats and renters. Check your address and ask about prepaid or postpaid router plans in English.",
    h1: "5G Home Internet in Jeddah",
    eyebrow: "Jeddah / Internet for your rental",
    city: "Jeddah",
    service: "5G home internet",
    intro: "Just moved into a Jeddah rental? A 5G home router lets you avoid running fiber cables through a property you do not own. Setup can begin quickly after the operator approves and activates your plan, without waiting for a fiber technician. Moving it to a future apartment depends on coverage and the subscription's location conditions.",
    contextTitle: "From a furnished flat to a compound home",
    context: "If you are renting a furnished apartment, living in a compound or sharing a flat in a Jeddah apartment building, check whether internet is already included in the lease. An independent router may give you a separate connection, but indoor reception needs checking at your own location. Tell us your housing type so we can discuss practical setup without assuming any compound or building is covered.",
    points: ["A separate connection for a furnished rental", "Prepaid and postpaid enquiries welcome", "Check indoor reception before choosing"],
    operatorIntro: "For Jeddah, we compare enquiries across STC, Zain, Salam and Mobily using your actual location. An operator appearing in this list is not a promise of service at your apartment.",
    operators: [
      ["STC", "Request the home-router choices that can be checked for your Jeddah address."],
      ["Zain", "Ask which home 5G plans and equipment conditions apply to your enquiry."],
      ["Salam", "Review any eligible router options and the current payment terms with us."],
      ["Mobily", "Include Mobily in the comparison and confirm its plan's location conditions."],
    ],
    requirements: ["Your valid Iqama or National ID; the provider confirms whether you qualify.", "A National Address or map pin for the Jeddah building where the router will be used.", "A working mobile number for application and activation messages."],
    steps: [
      ["Send your location", "Tell us your Jeddah area and share the location of the apartment or compound."],
      ["We check coverage", "We check eligible networks for the address and explain indoor-signal considerations."],
      ["Choose a plan", "Review available payment types, router terms and any commitment before selecting."],
      ["Activation", "After approval, we help follow up on the router order and the operator's activation process."],
    ],
    benefits: [
      ["Fast WhatsApp contact", "Send one Jeddah enquiry and get a prompt reply about the checks needed."],
      ["Help in English", "Ask about your rental, the paperwork or a plan condition without translating the conversation."],
      ["A wider comparison", "We review the operators relevant to your address, not just the first advertised offer."],
      ["Follow-through", "We keep track of the request with you until the operator confirms the next activation steps."],
    ],
    faqs: [
      { q: "Can I apply for 5G home internet in Jeddah with an Iqama?", a: "A valid Iqama can be submitted for the operator's application checks. We help you understand the required details, but approval and verification remain with the provider." },
      { q: "Is there a prepaid router option for a short stay in Jeddah?", a: "Ask for the prepaid options currently available for your address. We confirm the payment period, equipment costs and conditions; a prepaid enquiry does not guarantee a no-commitment offer." },
      { q: "Will a 5G router work inside my compound apartment?", a: "We cannot confirm service for a compound or building without checking. Share your exact location; indoor reception can differ with the room, walls and where you place the router." },
      { q: "Can I take the router to another apartment in Jeddah?", a: "Possibly, if the plan allows use at the new location and the network is suitable there. Ask us to review the movement rules and the new address before relocating it." },
      { q: "Do I need a landlord's permission to install a 5G router?", a: "A plug-in 5G home router does not need fixed fiber cabling. Check your tenancy or compound rules for any restrictions on your own internet equipment." },
      { q: "Can you arrange my Jeddah enquiry in English?", a: "Yes. Message us in English with your Jeddah area and housing type. We explain the available choices and follow up on the application." },
    ],
  },
  {
    path: "/en/5g-home-internet-riyadh",
    arabicPath: "/riyadh",
    nav: "5G home internet in Riyadh",
    title: "5G Home Internet Riyadh | Router Plans & Coverage Check",
    description: "Find a 5G home router for your Riyadh rental. Compare operators, check your location and get English support with your application.",
    h1: "5G Home Internet in Riyadh",
    eyebrow: "Riyadh / Settle in, stay connected",
    city: "Riyadh",
    service: "5G home internet",
    intro: "Starting a new job in Riyadh often means finding internet before deciding on a long-term home. A 5G router needs no fixed cabling and avoids a fiber installation visit, so getting started can be simpler once the service is approved. If you later change your rental, reuse depends on the new address's coverage and your plan's movement rules.",
    contextTitle: "Internet that fits your Riyadh housing plans",
    context: "A serviced or furnished apartment can be a first stop before a family flat, a compound or a villa. For a flat in a larger apartment building, shared Wi-Fi may not match your work needs; for a multi-room home, the router's position matters. Share the home you use now rather than a broad neighbourhood name. We do not infer coverage from the property type or a nearby office.",
    points: ["A practical option while settling into a new job", "Discuss video calls and household use", "Recheck the address before a move"],
    operatorIntro: "Riyadh enquiries can include STC, Zain, Salam and Mobily. We begin with eligibility at your location and then discuss plans, rather than ranking networks for the whole city.",
    operators: [
      ["STC", "Check the home 5G offer that applies to your current Riyadh residence."],
      ["Zain", "Compare the subscription and router conditions against your expected length of stay."],
      ["Salam", "Ask whether an eligible home internet option fits your work and household use."],
      ["Mobily", "Review location restrictions and the confirmed payment terms before applying."],
    ],
    requirements: ["A valid resident Iqama or Saudi National ID, subject to the chosen network's verification.", "The National Address or precise building pin for your Riyadh residence.", "Your mobile number so the provider can contact you about the request."],
    steps: [
      ["Send your location", "Share the Riyadh home address where you will use the connection, plus your housing type."],
      ["We check coverage", "We review services for that location and discuss signal checks inside the home."],
      ["Choose a plan", "Consider contract length, payment structure and your work-from-home requirements together."],
      ["Activation", "We track the application and help you understand the provider's setup instructions after approval."],
    ],
    benefits: [
      ["Prompt replies on WhatsApp", "Get the information needed to move your Riyadh enquiry forward without a store visit just to ask."],
      ["English explanations", "Understand commitment periods and application requirements in the language you prefer."],
      ["Provider comparison", "We put eligible plans in context for your lease and work routine."],
      ["Application follow-up", "Stay in touch about documents, operator responses and activation progress."],
    ],
    faqs: [
      { q: "Can a newly arrived Riyadh resident apply with an Iqama?", a: "Send an enquiry once you have a valid Iqama and a home location. The operator decides eligibility and may require further verification before accepting an order." },
      { q: "Is a prepaid plan suitable while I look for a permanent home?", a: "It may be worth comparing, but first check which prepaid offers are actually available and what they require upfront. We also explain any router conditions or usage restrictions." },
      { q: "Can I move my router from a furnished flat to a Riyadh compound?", a: "The new residence needs its own location check, and the subscription must permit the move. Do not assume that a connection working in your furnished flat will perform the same way in the compound." },
      { q: "Is home 5G reliable enough for remote work in Riyadh?", a: "Performance depends on signal indoors, network demand and router placement. Tell us if video meetings or large uploads are essential; eligible fiber may also be worth comparing, without guaranteeing a particular speed." },
      { q: "Does a larger apartment need more than one router?", a: "Room layout and walls affect Wi-Fi reach independently of the mobile network signal. Discuss your floor plan before buying additional equipment; a 5G plan alone does not guarantee Wi-Fi in every room." },
      { q: "Do you support Riyadh orders in English?", a: "Yes, we can discuss the location check, plan comparison and order updates in English over WhatsApp. Call 0564612017 if you prefer to speak directly." },
    ],
  },
  {
    path: "/en/5g-home-internet-khobar",
    arabicPath: "/khobar",
    nav: "5G home internet in Khobar",
    title: "5G Home Internet Khobar | Plans & English Support",
    description: "Explore 5G home internet for your Khobar apartment or compound. Request an address check and compare router plans with English help.",
    h1: "5G Home Internet in Khobar",
    eyebrow: "Khobar / Your own home connection",
    city: "Khobar",
    service: "5G home internet",
    intro: "Looking for your own connection in a Khobar rental? Home 5G uses a router rather than a fixed fiber cable, making it a useful option when you cannot alter the property. There is no fiber cabling appointment to wait for, although order approval and activation still apply. Taking the router to your next home requires suitable coverage and permission under the plan.",
    contextTitle: "For compound living and independent rentals",
    context: "Whether your Khobar home is in an expat compound, a furnished rental or an apartment block, ask what the rent includes before ordering another connection. Compound-managed internet may have its own arrangements, while a private flat may let you choose independently. Give us the specific residence for a check: neither a compound name nor a building category confirms network availability.",
    points: ["Check what your compound or lease includes", "Compare a private router with existing Wi-Fi", "Confirm terms for a future relocation"],
    operatorIntro: "We can look at STC, Zain, Salam and Mobily when reviewing a Khobar enquiry. Each choice is subject to a location check and the operator's current application terms.",
    operators: [
      ["STC", "Discuss whether its address-eligible home router plans suit your tenancy."],
      ["Zain", "Request a comparison of the equipment, payment period and movement rules."],
      ["Salam", "Include its home internet choices in the check instead of assuming only one provider is possible."],
      ["Mobily", "Confirm the applicable offer and service conditions for the exact Khobar home."],
    ],
    requirements: ["An in-date Iqama or National ID for identity and subscription eligibility checks.", "Your National Address or a map location identifying the Khobar building or compound residence.", "A mobile contact number for the operator and our order follow-up."],
    steps: [
      ["Send your location", "Tell us the Khobar area and pinpoint the residence, including a compound location if relevant."],
      ["We check coverage", "We assess which provider options can be requested, without promising indoor performance."],
      ["Choose a plan", "Compare the confirmed terms against your lease, existing internet and expected stay."],
      ["Activation", "We follow the order with you and clarify the operator's approval and activation updates."],
    ],
    benefits: [
      ["Quick WhatsApp response", "Get help narrowing down your Khobar home enquiry from the first message."],
      ["English-speaking assistance", "Discuss compound rules or subscription conditions without relying on literal translations."],
      ["Compare available networks", "Consider more than one operator when your address check allows it."],
      ["Continued order support", "We keep following the request rather than leaving you to interpret activation updates alone."],
    ],
    faqs: [
      { q: "What documents does an expat need for home 5G in Khobar?", a: "Start with a valid Iqama, your National Address or building location, and a mobile number. The provider confirms identity checks and any additional documents needed for the plan." },
      { q: "Can I order my own router inside a Khobar compound?", a: "Check your tenancy or compound management rules and share the specific residence for a network check. We do not claim that any compound has coverage or permits every service." },
      { q: "Can you check prepaid home internet for a temporary Khobar stay?", a: "Yes, we can enquire about eligible prepaid choices and explain the upfront payment and router terms. Their availability must be confirmed rather than assumed from the length of your stay." },
      { q: "Can the same home router be used at my workplace?", a: "Only if the subscription's location and usage conditions allow it and the other location is suitable. A home internet plan should not be treated as an unrestricted mobile connection." },
      { q: "What if I move from Khobar to another Saudi city?", a: "Before moving, check the operator's transfer or movement policy and availability at the new address. Owning the router does not guarantee that the existing plan can move with you." },
      { q: "Can I speak to someone in English about my Khobar order?", a: "Yes. Use WhatsApp in English to share your housing details and questions. We help compare the confirmed options and keep you informed about the application." },
    ],
  },
  {
    path: "/en/fiber-internet-jeddah",
    arabicPath: "/jeddah/stc",
    nav: "Fiber internet in Jeddah",
    title: "Fiber Internet Jeddah | STC, Salam & Mobily Plans",
    description: "Check fiber internet at your Jeddah building. Explore STC, Salam and Mobily, published STC prices and English-speaking application help.",
    h1: "Fiber Internet in Jeddah",
    eyebrow: "Jeddah / A connection for a longer stay",
    city: "Jeddah",
    service: "fiber internet",
    intro: "Planning to stay in your Jeddah home and want to explore fiber? Start with a check of the exact building and permission for any installation work. If you are a tenant who needs to avoid cabling, a 5G router is another option: it can start without a fiber technician once activated and may move with you, depending on coverage and plan restrictions.",
    contextTitle: "Check the building and the lease together",
    context: "For an expat renting in a Jeddah apartment block, a furnished unit or a compound, fiber decisions involve more than the neighbourhood. Ask the landlord or management about installation access and existing wiring. We check the building location independently and help you review the practical steps; a fibre box nearby or a neighbour's subscription is not confirmation for your own unit.",
    points: ["Building-level eligibility comes first", "Agree installation access with the landlord", "Compare fiber with a no-cabling 5G option"],
    operatorIntro: "STC, Salam and Mobily are options to discuss for a Jeddah fiber enquiry. We also consider Zain where its service can be confirmed, keeping fiber eligibility separate from any home 5G offer.",
    operators: [
      ["STC", "The STC table below translates the published Arabic Jeddah page; confirm the live offer before ordering."],
      ["Zain", "Ask for a building-specific fiber check; a router offer does not prove fiber availability."],
      ["Salam", "Enquire about the fiber service and terms that can be confirmed for your unit."],
      ["Mobily", "Review eligible fiber packages and installation arrangements at the actual address."],
    ],
    requirements: ["A valid Iqama or Saudi National ID, with final verification carried out by the fiber provider.", "The National Address or exact building location in Jeddah for the fiber check.", "A mobile number for application updates and coordination of the installation appointment."],
    steps: [
      ["Send your location", "Identify your Jeddah building and unit, and tell us whether you rent the property."],
      ["We check coverage", "We verify building-level fiber eligibility before discussing an installation request."],
      ["Choose a plan", "Review the available package, confirmed price, commitment and landlord-access requirements."],
      ["Activation", "We follow up on installation scheduling and the operator's service activation."],
    ],
    benefits: [
      ["Responsive WhatsApp help", "Get a quick reply about the address and building details needed for a fiber enquiry."],
      ["Clear English guidance", "Understand installation arrangements and the paperwork before agreeing to a package."],
      ["Compare eligible operators", "When more than one service is confirmed, we help compare terms rather than promising a specific network."],
      ["Installation follow-up", "Keep one point of contact while the provider processes the request and arranges activation."],
    ],
    faqs: [
      { q: "Is fiber available in my Jeddah building?", a: "We need the exact building location to check. Availability cannot be confirmed from the neighbourhood name, a nearby installation or a listing on this page." },
      { q: "Can a tenant with an Iqama apply for fiber?", a: "A valid Iqama can be used for an operator eligibility check. You also need to arrange the landlord's permission for cabling or access where required; the operator makes the final approval decision." },
      { q: "Are there prepaid STC fiber packages?", a: "The translated STC table includes the 12-month prepaid entries published on the Arabic Jeddah page. Ask us to confirm current eligibility, payment and offer conditions before relying on those published prices." },
      { q: "How is fiber different from a 5G router for a furnished apartment?", a: "Fiber requires building eligibility and may involve technician access and cabling. A 5G router avoids fixed wiring, but its performance depends on indoor signal and the plan's location terms." },
      { q: "Can I transfer fiber when I leave my apartment?", a: "A move normally needs an operator transfer request and a coverage check for the new building. Confirm the policy and any charges before changing address." },
      { q: "Can you explain fiber installation in English?", a: "Yes. We can explain the documents, package conditions and installation follow-up in English. The operator confirms the actual appointment and activation arrangements." },
    ],
  },
  {
    path: "/en/fiber-vs-5g",
    arabicPath: "/fiber-vs-5g",
    nav: "Compare fiber vs 5G",
    title: "Fiber vs 5G Home Internet in Saudi Arabia | Saudi Wasel",
    description: "Fiber or a 5G router for your Saudi rental? Compare installation, moving home and everyday use, with address checks and English support.",
    h1: "Fiber vs 5G Home Internet in Saudi Arabia",
    eyebrow: "The right connection for your lease",
    service: "fiber and 5G home internet comparison",
    intro: "For an expat renter, the best home internet choice is not always the largest speed on an advert. A 5G router skips fixed cabling, can be set up quickly after activation and may move with your rental plans, subject to location rules and coverage. Fiber needs building eligibility and installation arrangements but is worth comparing for a settled home and demanding daily use.",
    contextTitle: "Think about your next move as well as today",
    context: "If your lease is short, factor in commitment periods and relocation terms before choosing either service. If your household depends on video meetings, gaming or regular uploads, compare connection consistency as well as cost. A confirmed building check and an honest discussion of indoor 5G signal are more useful than a city-wide claim that one technology always wins.",
    points: ["Compare installation, not just download speeds", "Ask what happens when you change address", "Match the plan to your household's needs"],
    operatorIntro: "Compare technology and provider separately. STC, Zain, Salam and Mobily may have different services and conditions at your address, so we confirm eligible choices before weighing fiber against 5G.",
    operators: [
      ["STC", "Review its address-eligible fiber or home 5G terms as separate subscriptions."],
      ["Zain", "Compare any confirmed home service with your installation and mobility needs."],
      ["Salam", "Ask which connection type is available to order and how its commitment works."],
      ["Mobily", "Consider the applicable package's equipment and relocation conditions, not only the headline speed."],
    ],
    requirements: ["A valid Iqama or National ID for an application to whichever operator you select.", "Your National Address or building pin so fiber and 5G can be checked separately.", "A mobile number for eligibility queries, order updates and any installation coordination."],
    steps: [
      ["Send your location", "Share the home address, length of stay and what you use the internet for."],
      ["We check coverage", "We assess fiber eligibility and home 5G options independently at that location."],
      ["Choose a plan", "Balance installation, signal, payment and commitment using the confirmed offers."],
      ["Activation", "We follow the selected route: a router order for 5G or installation arrangements for fiber."],
    ],
    benefits: [
      ["Quick answers on WhatsApp", "Ask the practical questions about your lease and connection before starting an application."],
      ["English-led comparison", "Talk through cabling, moving home and plan restrictions in everyday language."],
      ["Operator choice", "Compare providers as well as technologies when more than one option is eligible."],
      ["Follow-up after choosing", "We continue helping with the order once you have made the fiber-or-5G decision."],
    ],
    faqs: [
      { q: "Is fiber or 5G better for an expat renting in Saudi Arabia?", a: "For a short stay, 5G's lack of fixed cabling can be practical, subject to the plan's commitment and location terms. For a longer stay, compare eligible fiber with your household's consistency and upload needs." },
      { q: "Which connection is easier to move to a new home?", a: "Some 5G plans allow movement, but you must check the new location and the specific restrictions. Fiber generally needs a transfer request and eligibility at the new building; neither move should be assumed automatic." },
      { q: "Is fiber always faster than a 5G home router?", a: "No universal speed can be promised. Fiber usually offers a more consistent connection, while 5G varies with indoor signal, router placement and network load. Review actual plan terms rather than comparing advertised maximums alone." },
      { q: "Can I apply for either service using an Iqama?", a: "A valid Iqama is a starting document for operator eligibility checks on both services. Application approval and any additional verification depend on the provider and chosen package." },
      { q: "Does prepaid internet mean I can cancel without restrictions?", a: "Not necessarily. Check equipment obligations, advance payments, commitment and refund or cancellation terms. We help you review confirmed prepaid and postpaid choices before you decide." },
      { q: "Can you help me compare fiber and 5G in English?", a: "Yes. Send your address, housing type and main uses on WhatsApp in English. We explain what can be checked and help compare the options the operators confirm." },
    ],
  },
];

export const englishDisclaimer = "Saudi Wasel is an independent sales agent and is not the official website of any telecom operator.";
export const priceEnquiry = "Contact us on WhatsApp for the latest plans and prices available at your address.";

export function englishMetadata(page) {
  return {
    title: page.title,
    description: page.description,
    alternates: { canonical: page.path, languages: languageAlternates(page.arabicPath) },
    openGraph: {
      title: page.title,
      description: page.description,
      url: page.path,
      locale: "en_SA",
      alternateLocale: "ar_SA",
      siteName: "Saudi Wasel",
      type: "website",
      images: [{ url: "/opengraph-image.png", alt: "Saudi Wasel home internet" }],
    },
    twitter: { card: "summary_large_image", title: page.title, description: page.description, images: ["/twitter-image.png"] },
  };
}

const stcPlanNames = {
  "بيتي فايبر بيسك": "Baity Fiber Basic",
  "بيتي ستريم لايت": "Baity Stream Lite",
  "بيتي فايبر ستريم": "Baity Fiber Stream",
  "بيتي فايبر انترتينمنت": "Baity Fiber Entertainment",
  "500 ميجا مسبق الدفع 12 شهر": "500 Mbps prepaid, 12 months",
  "300 ميجا مسبق الدفع 12 شهر": "300 Mbps prepaid, 12 months",
};
const stcPerks = {
  "مودم وتركيب مجاني + stc tv": "Free modem and installation + stc tv",
  "stc tv + منصة بث واحدة": "stc tv + one streaming platform",
  "stc tv + منصتين بث": "stc tv + two streaming platforms",
  "تركيب ومودم مجاني + شهرين مجاناً": "Free installation and modem + two free months",
};
const stc = operators.find((operator) => operator.slug === "stc");
export const stcPricesUpdated = stc.updatedISO;
export const englishStcPlans = stc.packages.map((plan) => ({
  name: stcPlanNames[plan.name],
  down: plan.down.replace("ميجا", "Mbps"),
  up: plan.up.replace("ميجا", "Mbps"),
  price: plan.price.replace("ريال/شهر", "SAR/month").replace("ريال/سنة", "SAR/year").replace("عرض", "offer"),
  perks: stcPerks[plan.perks],
}));

export const connectionComparison = [
  ["Getting connected", "Building check, cabling if needed, and a technician appointment.", "A plug-in router; no fixed fiber cabling, once the operator activates service."],
  ["For a tenant", "Arrange landlord or management permission for installation work.", "No fixed wiring; check your tenancy or compound's equipment rules."],
  ["Connection consistency", "Typically a steadier fixed connection; actual service and plan still matter.", "Depends on indoor signal, router placement and network demand."],
  ["Uploads and gaming", "Often worth considering for frequent uploads or latency-sensitive use.", "Check real conditions and your usage needs; no speed or latency is guaranteed."],
  ["Moving home", "An operator transfer request and a check of the new building.", "Only where the subscription allows movement and the new location is suitable."],
  ["Availability", "Must be confirmed for the exact building.", "Requires a location check; indoor performance can differ between rooms."],
  ["Plans and pricing", "Review the confirmed price, installation terms and commitment.", "Compare eligible prepaid or postpaid offers and router obligations."],
];
